-- This script was auto generated by dataship on 2019-04-04 12:11 

DROP TABLE  if exists tmp.tmp_contract_payment; 
CREATE TABLE tmp.tmp_contract_payment 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`contract_id`, t2.`contract_id`) as `contract_id`,
  coalesce(t1.`order_id`, t2.`order_id`) as `order_id`,
  coalesce(t1.`trade_no`, t2.`trade_no`) as `trade_no`,
  coalesce(t1.`pay_type`, t2.`pay_type`) as `pay_type`,
  coalesce(t1.`amount`, t2.`amount`) as `amount`,
  coalesce(t1.`total_fee`, t2.`total_fee`) as `total_fee`,
  coalesce(t1.`card_coupons_fee`, t2.`card_coupons_fee`) as `card_coupons_fee`,
  coalesce(t1.`card_coupons_detail_id`, t2.`card_coupons_detail_id`) as `card_coupons_detail_id`,
  coalesce(t1.`card_coupons_status`, t2.`card_coupons_status`) as `card_coupons_status`,
  coalesce(t1.`response_code`, t2.`response_code`) as `response_code`,
  coalesce(t1.`callback_code`, t2.`callback_code`) as `callback_code`,
  coalesce(t1.`is_success`, t2.`is_success`) as `is_success`,
  coalesce(t1.`update_at`, t2.`update_at`) as `update_at`,
  coalesce(t1.`create_at`, t2.`create_at`) as `create_at`,
  coalesce(t1.`operator_type`, t2.`operator_type`) as `operator_type`,
  coalesce(t1.`operator_id`, t2.`operator_id`) as `operator_id`,
  coalesce(t1.`student_id`, t2.`student_id`) as `student_id`,
  coalesce(t1.`success_at`, t2.`success_at`) as `success_at`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `contract_id`, 
    `order_id`, 
    `trade_no`, 
    `pay_type`, 
    `amount`, 
    `total_fee`, 
    `card_coupons_fee`, 
    `card_coupons_detail_id`, 
    `card_coupons_status`, 
    `response_code`, 
    `callback_code`, 
    `is_success`, 
    `update_at`, 
    `create_at`, 
    `operator_type`, 
    `operator_id`, 
    `student_id`, 
    `success_at`, 
    `load_time` 
  FROM stg.newuuabc_contract_payment 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `contract_id`, 
    `order_id`, 
    `trade_no`, 
    `pay_type`, 
    `amount`, 
    `total_fee`, 
    `card_coupons_fee`, 
    `card_coupons_detail_id`, 
    `card_coupons_status`, 
    `response_code`, 
    `callback_code`, 
    `is_success`, 
    `update_at`, 
    `create_at`, 
    `operator_type`, 
    `operator_id`, 
    `student_id`, 
    `success_at`, 
    `load_time`
  FROM ods.newuuabc_contract_payment 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.newuuabc_contract_payment  
SELECT
  `id`, 
  `contract_id`, 
  `order_id`, 
  `trade_no`, 
  `pay_type`, 
  `amount`, 
  `total_fee`, 
  `card_coupons_fee`, 
  `card_coupons_detail_id`, 
  `card_coupons_status`, 
  `response_code`, 
  `callback_code`, 
  `is_success`, 
  `update_at`, 
  `create_at`, 
  `operator_type`, 
  `operator_id`, 
  `student_id`, 
  `success_at`, 
  `load_time`
FROM tmp.tmp_contract_payment; 

