-- This script was auto generated by dataship on 2019-03-08 10:31 

DROP TABLE  if exists tmp.tmp_application_log; 
CREATE TABLE tmp.tmp_application_log 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`user_id`, t2.`user_id`) as `user_id`,
  coalesce(t1.`course_id`, t2.`course_id`) as `course_id`,
  coalesce(t1.`operating_time`, t2.`operating_time`) as `operating_time`,
  coalesce(t1.`controller`, t2.`controller`) as `controller`,
  coalesce(t1.`method`, t2.`method`) as `method`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`operating_text`, t2.`operating_text`) as `operating_text`,
  coalesce(t1.`operating`, t2.`operating`) as `operating`,
  coalesce(t1.`type`, t2.`type`) as `type`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `user_id`, 
    `course_id`, 
    `operating_time`, 
    `controller`, 
    `method`, 
    `status`, 
    `operating_text`, 
    `operating`, 
    `type`, 
    `load_time` 
  FROM stg.newuuabc_application_log 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `user_id`, 
    `course_id`, 
    `operating_time`, 
    `controller`, 
    `method`, 
    `status`, 
    `operating_text`, 
    `operating`, 
    `type`, 
    `load_time`
  FROM ods.newuuabc_application_log 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.newuuabc_application_log  
SELECT
  `id`, 
  `user_id`, 
  `course_id`, 
  `operating_time`, 
  `controller`, 
  `method`, 
  `status`, 
  `operating_text`, 
  `operating`, 
  `type`, 
  `load_time`
FROM tmp.tmp_application_log; 

