-- This script was auto generated by dataship on 2019-03-07 15:22 

DROP TABLE  if exists tmp.tmp_student_evaluate; 
CREATE TABLE tmp.tmp_student_evaluate 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`student_user_id`, t2.`student_user_id`) as `student_user_id`,
  coalesce(t1.`appoint_course_id`, t2.`appoint_course_id`) as `appoint_course_id`,
  coalesce(t1.`class_appoint_course_id`, t2.`class_appoint_course_id`) as `class_appoint_course_id`,
  coalesce(t1.`evaluate_type`, t2.`evaluate_type`) as `evaluate_type`,
  coalesce(t1.`evaluate_content`, t2.`evaluate_content`) as `evaluate_content`,
  coalesce(t1.`evaluate_level`, t2.`evaluate_level`) as `evaluate_level`,
  coalesce(t1.`teacher_evaluate`, t2.`teacher_evaluate`) as `teacher_evaluate`,
  coalesce(t1.`service_evaluate`, t2.`service_evaluate`) as `service_evaluate`,
  coalesce(t1.`platform_evaluate`, t2.`platform_evaluate`) as `platform_evaluate`,
  coalesce(t1.`from`, t2.`from`) as `from`,
  coalesce(t1.`type`, t2.`type`) as `type`,
  coalesce(t1.`created`, t2.`created`) as `created`,
  coalesce(t1.`updated`, t2.`updated`) as `updated`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `student_user_id`, 
    `appoint_course_id`, 
    `class_appoint_course_id`, 
    `evaluate_type`, 
    `evaluate_content`, 
    `evaluate_level`, 
    `teacher_evaluate`, 
    `service_evaluate`, 
    `platform_evaluate`, 
    `from`, 
    `type`, 
    `created`, 
    `updated`, 
    `load_time` 
  FROM stg.newuuabc_student_evaluate 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `student_user_id`, 
    `appoint_course_id`, 
    `class_appoint_course_id`, 
    `evaluate_type`, 
    `evaluate_content`, 
    `evaluate_level`, 
    `teacher_evaluate`, 
    `service_evaluate`, 
    `platform_evaluate`, 
    `from`, 
    `type`, 
    `created`, 
    `updated`, 
    `load_time`
  FROM ods.newuuabc_student_evaluate 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.newuuabc_student_evaluate  
SELECT
  `id`, 
  `student_user_id`, 
  `appoint_course_id`, 
  `class_appoint_course_id`, 
  `evaluate_type`, 
  `evaluate_content`, 
  `evaluate_level`, 
  `teacher_evaluate`, 
  `service_evaluate`, 
  `platform_evaluate`, 
  `from`, 
  `type`, 
  `created`, 
  `updated`, 
  `load_time`
FROM tmp.tmp_student_evaluate; 

