-- This script was auto generated by dataship on 2019-03-11 18:25 

DROP TABLE  if exists tmp.tmp_student_class; 
CREATE TABLE tmp.tmp_student_class 
USING PARQUET
AS SELECT
  coalesce(t1.`student_class_id`, t2.`student_class_id`) as `student_class_id`,
  coalesce(t1.`train_id`, t2.`train_id`) as `train_id`,
  coalesce(t1.`student_id`, t2.`student_id`) as `student_id`,
  coalesce(t1.`teacher_id`, t2.`teacher_id`) as `teacher_id`,
  coalesce(t1.`course_flag`, t2.`course_flag`) as `course_flag`,
  coalesce(t1.`class_type`, t2.`class_type`) as `class_type`,
  coalesce(t1.`class_date`, t2.`class_date`) as `class_date`,
  coalesce(t1.`book_type`, t2.`book_type`) as `book_type`,
  coalesce(t1.`seat_type`, t2.`seat_type`) as `seat_type`,
  coalesce(t1.`start_carport`, t2.`start_carport`) as `start_carport`,
  coalesce(t1.`end_carport`, t2.`end_carport`) as `end_carport`,
  coalesce(t1.`start_time`, t2.`start_time`) as `start_time`,
  coalesce(t1.`end_time`, t2.`end_time`) as `end_time`,
  coalesce(t1.`lesson_category`, t2.`lesson_category`) as `lesson_category`,
  coalesce(t1.`lesson`, t2.`lesson`) as `lesson`,
  coalesce(t1.`room_id`, t2.`room_id`) as `room_id`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`create_date`, t2.`create_date`) as `create_date`,
  coalesce(t1.`update_date`, t2.`update_date`) as `update_date`,
  coalesce(t1.`operator_id`, t2.`operator_id`) as `operator_id`,
  coalesce(t1.`student_entry_time`, t2.`student_entry_time`) as `student_entry_time`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `student_class_id`, 
    `train_id`, 
    `student_id`, 
    `teacher_id`, 
    `course_flag`, 
    `class_type`, 
    `class_date`, 
    `book_type`, 
    `seat_type`, 
    `start_carport`, 
    `end_carport`, 
    `start_time`, 
    `end_time`, 
    `lesson_category`, 
    `lesson`, 
    `room_id`, 
    `status`, 
    `create_date`, 
    `update_date`, 
    `operator_id`, 
    `student_entry_time`, 
    `load_time` 
  FROM stg.classbooking_student_class 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `student_class_id`, 
    `train_id`, 
    `student_id`, 
    `teacher_id`, 
    `course_flag`, 
    `class_type`, 
    `class_date`, 
    `book_type`, 
    `seat_type`, 
    `start_carport`, 
    `end_carport`, 
    `start_time`, 
    `end_time`, 
    `lesson_category`, 
    `lesson`, 
    `room_id`, 
    `status`, 
    `create_date`, 
    `update_date`, 
    `operator_id`, 
    `student_entry_time`, 
    `load_time`
  FROM ods.classbooking_student_class 
) t2 
  ON t1.`student_class_id` = t2.`student_class_id`
;



INSERT OVERWRITE TABLE ods.classbooking_student_class  
SELECT
  `student_class_id`, 
  `train_id`, 
  `student_id`, 
  `teacher_id`, 
  `course_flag`, 
  `class_type`, 
  `class_date`, 
  `book_type`, 
  `seat_type`, 
  `start_carport`, 
  `end_carport`, 
  `start_time`, 
  `end_time`, 
  `lesson_category`, 
  `lesson`, 
  `room_id`, 
  `status`, 
  `create_date`, 
  `update_date`, 
  `operator_id`, 
  `student_entry_time`, 
  `load_time`
FROM tmp.tmp_student_class; 

