-- This script was auto generated by dataship on 2019-03-21 19:13 

INSERT OVERWRITE TABLE ods.newuuabc_department
SELECT
  `id` ,
  `depart_name` ,
  `created_at` ,
  `updated_at` ,
  `pid` ,
  `level` ,
  `has_children` ,
  `status` ,
  `topid` ,
  load_time
FROM stg.newuuabc_department
WHERE etl_date = '{{ macros.ds(ti) }}'; 


