-- This script was auto generated by dataship on 2019-01-29 19:45 

DROP TABLE  if exists tmp.tmp_train; 
CREATE TABLE tmp.tmp_train 
USING PARQUET
AS SELECT
  coalesce(t1.`train_id`, t2.`train_id`) as `train_id`,
  coalesce(t1.`name`, t2.`name`) as `name`,
  coalesce(t1.`start_date`, t2.`start_date`) as `start_date`,
  coalesce(t1.`finish_date`, t2.`finish_date`) as `finish_date`,
  coalesce(t1.`class_type`, t2.`class_type`) as `class_type`,
  coalesce(t1.`lesson_category`, t2.`lesson_category`) as `lesson_category`,
  coalesce(t1.`lesson_count`, t2.`lesson_count`) as `lesson_count`,
  coalesce(t1.`start_lesson`, t2.`start_lesson`) as `start_lesson`,
  coalesce(t1.`last_progress`, t2.`last_progress`) as `last_progress`,
  coalesce(t1.`loop`, t2.`loop`) as `loop`,
  coalesce(t1.`frequency`, t2.`frequency`) as `frequency`,
  coalesce(t1.`current_period`, t2.`current_period`) as `current_period`,
  coalesce(t1.`schedule_period`, t2.`schedule_period`) as `schedule_period`,
  coalesce(t1.`schedule_progress`, t2.`schedule_progress`) as `schedule_progress`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`init_count`, t2.`init_count`) as `init_count`,
  coalesce(t1.`max_headcount`, t2.`max_headcount`) as `max_headcount`,
  coalesce(t1.`description`, t2.`description`) as `description`,
  coalesce(t1.`create_date`, t2.`create_date`) as `create_date`,
  coalesce(t1.`update_date`, t2.`update_date`) as `update_date`,
  coalesce(t1.`operator_id`, t2.`operator_id`) as `operator_id`,
  coalesce(t1.`sortby`, t2.`sortby`) as `sortby`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `train_id`, 
    `name`, 
    `start_date`, 
    `finish_date`, 
    `class_type`, 
    `lesson_category`, 
    `lesson_count`, 
    `start_lesson`, 
    `last_progress`, 
    `loop`, 
    `frequency`, 
    `current_period`, 
    `schedule_period`, 
    `schedule_progress`, 
    `status`, 
    `init_count`, 
    `max_headcount`, 
    `description`, 
    `create_date`, 
    `update_date`, 
    `operator_id`, 
    `sortby`, 
    `load_time` 
  FROM stg.classschedule_train 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `train_id`, 
    `name`, 
    `start_date`, 
    `finish_date`, 
    `class_type`, 
    `lesson_category`, 
    `lesson_count`, 
    `start_lesson`, 
    `last_progress`, 
    `loop`, 
    `frequency`, 
    `current_period`, 
    `schedule_period`, 
    `schedule_progress`, 
    `status`, 
    `init_count`, 
    `max_headcount`, 
    `description`, 
    `create_date`, 
    `update_date`, 
    `operator_id`, 
    `sortby`, 
    `load_time`
  FROM ods.classschedule_train 
) t2 
  ON t1.`train_id` = t2.`train_id`
;



INSERT OVERWRITE TABLE ods.classschedule_train  
SELECT
  `train_id`, 
  `name`, 
  `start_date`, 
  `finish_date`, 
  `class_type`, 
  `lesson_category`, 
  `lesson_count`, 
  `start_lesson`, 
  `last_progress`, 
  `loop`, 
  `frequency`, 
  `current_period`, 
  `schedule_period`, 
  `schedule_progress`, 
  `status`, 
  `init_count`, 
  `max_headcount`, 
  `description`, 
  `create_date`, 
  `update_date`, 
  `operator_id`, 
  `sortby`, 
  `load_time`
FROM tmp.tmp_train; 

