-- This script was auto generated by dataship on 2019-03-19 11:47 

INSERT OVERWRITE TABLE ods.sishu_bk_subject
SELECT
  `id` ,
  `cl_id` ,
  `tnameid` ,
  `cpdate` ,
  `cpdatei` ,
  `status` ,
  `teacher_status` ,
  `homework` ,
  `notes` ,
  `photo` ,
  `sum_sk` ,
  `sum_qj` ,
  `sum_kk` ,
  `sum_st` ,
  `op_time` ,
  `op_uid` ,
  `fee_set` ,
  `times_id` ,
  `teacher_fee` ,
  `teacher_uid` ,
  `continued_time` ,
  `overtime` ,
  `late` ,
  `leave_early` ,
  `create_time` ,
  `update_time` ,
  load_time
FROM stg.sishu_bk_subject
WHERE etl_date = '{{ macros.ds(ti) }}'; 


