-- This script was auto generated by dataship on 2019-01-21 19:09 

DROP TABLE  if exists tmp.tmp_teacher_signed; 
CREATE TABLE tmp.tmp_teacher_signed 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`teacher_id`, t2.`teacher_id`) as `teacher_id`,
  coalesce(t1.`signed_type`, t2.`signed_type`) as `signed_type`,
  coalesce(t1.`signed_starttime`, t2.`signed_starttime`) as `signed_starttime`,
  coalesce(t1.`signed_endtime`, t2.`signed_endtime`) as `signed_endtime`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`enable`, t2.`enable`) as `enable`,
  coalesce(t1.`enable_time`, t2.`enable_time`) as `enable_time`,
  coalesce(t1.`create_user`, t2.`create_user`) as `create_user`,
  coalesce(t1.`created_at`, t2.`created_at`) as `created_at`,
  coalesce(t1.`updated_at`, t2.`updated_at`) as `updated_at`,
  coalesce(t1.`money_type`, t2.`money_type`) as `money_type`,
  coalesce(t1.`agree_time`, t2.`agree_time`) as `agree_time`,
  coalesce(t1.`level`, t2.`level`) as `level`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `teacher_id`, 
    `signed_type`, 
    `signed_starttime`, 
    `signed_endtime`, 
    `status`, 
    `enable`, 
    `enable_time`, 
    `create_user`, 
    `created_at`, 
    `updated_at`, 
    `money_type`, 
    `agree_time`, 
    `level`, 
    `load_time` 
  FROM stg.teacher_contract_teacher_signed 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `teacher_id`, 
    `signed_type`, 
    `signed_starttime`, 
    `signed_endtime`, 
    `status`, 
    `enable`, 
    `enable_time`, 
    `create_user`, 
    `created_at`, 
    `updated_at`, 
    `money_type`, 
    `agree_time`, 
    `level`, 
    `load_time`
  FROM ods.teacher_contract_teacher_signed 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.teacher_contract_teacher_signed  
SELECT
  `id`, 
  `teacher_id`, 
  `signed_type`, 
  `signed_starttime`, 
  `signed_endtime`, 
  `status`, 
  `enable`, 
  `enable_time`, 
  `create_user`, 
  `created_at`, 
  `updated_at`, 
  `money_type`, 
  `agree_time`, 
  `level`, 
  `load_time`
FROM tmp.tmp_teacher_signed; 

