-- This script was auto generated by dataship on 2019-03-19 11:47 

INSERT OVERWRITE TABLE ods.newuuabc_product_consume
SELECT
  `id` ,
  `type` ,
  `key` ,
  `stuId` ,
  `subjectId` ,
  `num` ,
  `contractId` ,
  `is_free` ,
  `status` ,
  `create_date` ,
  `update_date` ,
  load_time
FROM stg.newuuabc_product_consume
WHERE etl_date = '{{ macros.ds(ti) }}'; 


