-- This script was auto generated by dataship on 2019-01-21 19:09 

INSERT OVERWRITE TABLE ods.teacher_contract_carport_time
SELECT
  `id` ,
  `start_time` ,
  `end_time` ,
  load_time
FROM stg.teacher_contract_carport_time
WHERE etl_date = '{{ macros.ds(ti) }}'; 


