-- This script was auto generated by dataship on 2019-03-07 15:23 

DROP TABLE  if exists tmp.tmp_teacher_absenteeism; 
CREATE TABLE tmp.tmp_teacher_absenteeism 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`teacher_id`, t2.`teacher_id`) as `teacher_id`,
  coalesce(t1.`start_time`, t2.`start_time`) as `start_time`,
  coalesce(t1.`end_time`, t2.`end_time`) as `end_time`,
  coalesce(t1.`remarks`, t2.`remarks`) as `remarks`,
  coalesce(t1.`create_time`, t2.`create_time`) as `create_time`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`cancel_reason`, t2.`cancel_reason`) as `cancel_reason`,
  coalesce(t1.`update_at`, t2.`update_at`) as `update_at`,
  coalesce(t1.`operator_id`, t2.`operator_id`) as `operator_id`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `teacher_id`, 
    `start_time`, 
    `end_time`, 
    `remarks`, 
    `create_time`, 
    `status`, 
    `cancel_reason`, 
    `update_at`, 
    `operator_id`, 
    `load_time` 
  FROM stg.newuuabc_teacher_absenteeism 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `teacher_id`, 
    `start_time`, 
    `end_time`, 
    `remarks`, 
    `create_time`, 
    `status`, 
    `cancel_reason`, 
    `update_at`, 
    `operator_id`, 
    `load_time`
  FROM ods.newuuabc_teacher_absenteeism 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.newuuabc_teacher_absenteeism  
SELECT
  `id`, 
  `teacher_id`, 
  `start_time`, 
  `end_time`, 
  `remarks`, 
  `create_time`, 
  `status`, 
  `cancel_reason`, 
  `update_at`, 
  `operator_id`, 
  `load_time`
FROM tmp.tmp_teacher_absenteeism; 

