-- This script was auto generated by dataship on 2019-03-19 11:47 

INSERT OVERWRITE TABLE ods.newuuabc_parents
SELECT
  `id` ,
  `student_id` ,
  `footing` ,
  `name` ,
  `qq` ,
  `wechat` ,
  `phone` ,
  `email` ,
  `profession` ,
  `situation` ,
  `update_time` ,
  `create_time` ,
  `update_at` ,
  load_time
FROM stg.newuuabc_parents
WHERE etl_date = '{{ macros.ds(ti) }}'; 


