-- This script was auto generated by dataship on 2019-03-11 11:47 

DROP TABLE  if exists tmp.tmp_contract_refund; 
CREATE TABLE tmp.tmp_contract_refund 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`contract_id`, t2.`contract_id`) as `contract_id`,
  coalesce(t1.`contract_payment_id`, t2.`contract_payment_id`) as `contract_payment_id`,
  coalesce(t1.`student_id`, t2.`student_id`) as `student_id`,
  coalesce(t1.`template_id`, t2.`template_id`) as `template_id`,
  coalesce(t1.`fee`, t2.`fee`) as `fee`,
  coalesce(t1.`way`, t2.`way`) as `way`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`contract_snapshot`, t2.`contract_snapshot`) as `contract_snapshot`,
  coalesce(t1.`subject_snapshot`, t2.`subject_snapshot`) as `subject_snapshot`,
  coalesce(t1.`op_admin_id`, t2.`op_admin_id`) as `op_admin_id`,
  coalesce(t1.`refund_time`, t2.`refund_time`) as `refund_time`,
  coalesce(t1.`examine_admin_id`, t2.`examine_admin_id`) as `examine_admin_id`,
  coalesce(t1.`examine_time`, t2.`examine_time`) as `examine_time`,
  coalesce(t1.`create_admin_id`, t2.`create_admin_id`) as `create_admin_id`,
  coalesce(t1.`create_time`, t2.`create_time`) as `create_time`,
  coalesce(t1.`update_time`, t2.`update_time`) as `update_time`,
  coalesce(t1.`remarks`, t2.`remarks`) as `remarks`,
  coalesce(t1.`cancle_admin_id`, t2.`cancle_admin_id`) as `cancle_admin_id`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `contract_id`, 
    `contract_payment_id`, 
    `student_id`, 
    `template_id`, 
    `fee`, 
    `way`, 
    `status`, 
    `contract_snapshot`, 
    `subject_snapshot`, 
    `op_admin_id`, 
    `refund_time`, 
    `examine_admin_id`, 
    `examine_time`, 
    `create_admin_id`, 
    `create_time`, 
    `update_time`, 
    `remarks`, 
    `cancle_admin_id`, 
    `load_time` 
  FROM stg.newuuabc_contract_refund 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `contract_id`, 
    `contract_payment_id`, 
    `student_id`, 
    `template_id`, 
    `fee`, 
    `way`, 
    `status`, 
    `contract_snapshot`, 
    `subject_snapshot`, 
    `op_admin_id`, 
    `refund_time`, 
    `examine_admin_id`, 
    `examine_time`, 
    `create_admin_id`, 
    `create_time`, 
    `update_time`, 
    `remarks`, 
    `cancle_admin_id`, 
    `load_time`
  FROM ods.newuuabc_contract_refund 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.newuuabc_contract_refund  
SELECT
  `id`, 
  `contract_id`, 
  `contract_payment_id`, 
  `student_id`, 
  `template_id`, 
  `fee`, 
  `way`, 
  `status`, 
  `contract_snapshot`, 
  `subject_snapshot`, 
  `op_admin_id`, 
  `refund_time`, 
  `examine_admin_id`, 
  `examine_time`, 
  `create_admin_id`, 
  `create_time`, 
  `update_time`, 
  `remarks`, 
  `cancle_admin_id`, 
  `load_time`
FROM tmp.tmp_contract_refund; 

