-- This script was auto generated by dataship on 2019-03-07 15:23 

DROP TABLE  if exists tmp.tmp_bk_check; 
CREATE TABLE tmp.tmp_bk_check 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`type`, t2.`type`) as `type`,
  coalesce(t1.`typecn`, t2.`typecn`) as `typecn`,
  coalesce(t1.`sh`, t2.`sh`) as `sh`,
  coalesce(t1.`initiator_uid`, t2.`initiator_uid`) as `initiator_uid`,
  coalesce(t1.`addtime`, t2.`addtime`) as `addtime`,
  coalesce(t1.`edittime`, t2.`edittime`) as `edittime`,
  coalesce(t1.`endtime`, t2.`endtime`) as `endtime`,
  coalesce(t1.`rank`, t2.`rank`) as `rank`,
  coalesce(t1.`jnid`, t2.`jnid`) as `jnid`,
  coalesce(t1.`display`, t2.`display`) as `display`,
  coalesce(t1.`keywords`, t2.`keywords`) as `keywords`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `type`, 
    `typecn`, 
    `sh`, 
    `initiator_uid`, 
    `addtime`, 
    `edittime`, 
    `endtime`, 
    `rank`, 
    `jnid`, 
    `display`, 
    `keywords`, 
    `load_time` 
  FROM stg.sishu_bk_check 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `type`, 
    `typecn`, 
    `sh`, 
    `initiator_uid`, 
    `addtime`, 
    `edittime`, 
    `endtime`, 
    `rank`, 
    `jnid`, 
    `display`, 
    `keywords`, 
    `load_time`
  FROM ods.sishu_bk_check 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.sishu_bk_check  
SELECT
  `id`, 
  `type`, 
  `typecn`, 
  `sh`, 
  `initiator_uid`, 
  `addtime`, 
  `edittime`, 
  `endtime`, 
  `rank`, 
  `jnid`, 
  `display`, 
  `keywords`, 
  `load_time`
FROM tmp.tmp_bk_check; 

