-- This script was auto generated by dataship on 2019-01-21 19:09 

DROP TABLE  if exists tmp.tmp_teacher_signed_log; 
CREATE TABLE tmp.tmp_teacher_signed_log 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`signed_id`, t2.`signed_id`) as `signed_id`,
  coalesce(t1.`pre_signed`, t2.`pre_signed`) as `pre_signed`,
  coalesce(t1.`current_signed`, t2.`current_signed`) as `current_signed`,
  coalesce(t1.`action`, t2.`action`) as `action`,
  coalesce(t1.`created_at`, t2.`created_at`) as `created_at`,
  coalesce(t1.`updated_at`, t2.`updated_at`) as `updated_at`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `signed_id`, 
    `pre_signed`, 
    `current_signed`, 
    `action`, 
    `created_at`, 
    `updated_at`, 
    `load_time` 
  FROM stg.teacher_contract_teacher_signed_log 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `signed_id`, 
    `pre_signed`, 
    `current_signed`, 
    `action`, 
    `created_at`, 
    `updated_at`, 
    `load_time`
  FROM ods.teacher_contract_teacher_signed_log 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.teacher_contract_teacher_signed_log  
SELECT
  `id`, 
  `signed_id`, 
  `pre_signed`, 
  `current_signed`, 
  `action`, 
  `created_at`, 
  `updated_at`, 
  `load_time`
FROM tmp.tmp_teacher_signed_log; 

