-- This script was auto generated by dataship on 2019-03-07 15:22 

DROP TABLE  if exists tmp.tmp_bk_sign_in; 
CREATE TABLE tmp.tmp_bk_sign_in 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`uid`, t2.`uid`) as `uid`,
  coalesce(t1.`sign_status`, t2.`sign_status`) as `sign_status`,
  coalesce(t1.`sign_notes`, t2.`sign_notes`) as `sign_notes`,
  coalesce(t1.`sign_pic`, t2.`sign_pic`) as `sign_pic`,
  coalesce(t1.`clt_id`, t2.`clt_id`) as `clt_id`,
  coalesce(t1.`sign_location_x`, t2.`sign_location_x`) as `sign_location_x`,
  coalesce(t1.`sign_location_y`, t2.`sign_location_y`) as `sign_location_y`,
  coalesce(t1.`sign_origin`, t2.`sign_origin`) as `sign_origin`,
  coalesce(t1.`sign_location_text`, t2.`sign_location_text`) as `sign_location_text`,
  coalesce(t1.`sign_date`, t2.`sign_date`) as `sign_date`,
  coalesce(t1.`sign_date_unix`, t2.`sign_date_unix`) as `sign_date_unix`,
  coalesce(t1.`addtime`, t2.`addtime`) as `addtime`,
  coalesce(t1.`isplay`, t2.`isplay`) as `isplay`,
  coalesce(t1.`set_date`, t2.`set_date`) as `set_date`,
  coalesce(t1.`update_time`, t2.`update_time`) as `update_time`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `uid`, 
    `sign_status`, 
    `sign_notes`, 
    `sign_pic`, 
    `clt_id`, 
    `sign_location_x`, 
    `sign_location_y`, 
    `sign_origin`, 
    `sign_location_text`, 
    `sign_date`, 
    `sign_date_unix`, 
    `addtime`, 
    `isplay`, 
    `set_date`, 
    `update_time`, 
    `load_time` 
  FROM stg.sishu_bk_sign_in 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `uid`, 
    `sign_status`, 
    `sign_notes`, 
    `sign_pic`, 
    `clt_id`, 
    `sign_location_x`, 
    `sign_location_y`, 
    `sign_origin`, 
    `sign_location_text`, 
    `sign_date`, 
    `sign_date_unix`, 
    `addtime`, 
    `isplay`, 
    `set_date`, 
    `update_time`, 
    `load_time`
  FROM ods.sishu_bk_sign_in 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.sishu_bk_sign_in  
SELECT
  `id`, 
  `uid`, 
  `sign_status`, 
  `sign_notes`, 
  `sign_pic`, 
  `clt_id`, 
  `sign_location_x`, 
  `sign_location_y`, 
  `sign_origin`, 
  `sign_location_text`, 
  `sign_date`, 
  `sign_date_unix`, 
  `addtime`, 
  `isplay`, 
  `set_date`, 
  `update_time`, 
  `load_time`
FROM tmp.tmp_bk_sign_in; 

