-- This script was auto generated by dataship on 2019-03-19 11:47 

INSERT OVERWRITE TABLE ods.newuuabc_teacher_evaluate
SELECT
  `id` ,
  `teacher_user_id` ,
  `appoint_course_id` ,
  `class_appoint_course_id` ,
  `learning_rate` ,
  `good_suggest` ,
  `better_suggest` ,
  `homework_rate` ,
  `comment_type` ,
  `comment_star` ,
  `is_publish` ,
  `is_refused` ,
  `refused` ,
  `operator_id` ,
  `created` ,
  `updated` ,
  load_time
FROM stg.newuuabc_teacher_evaluate
WHERE etl_date = '{{ macros.ds(ti) }}'; 


