-- This script was auto generated by dataship on 2019-03-19 11:47 

INSERT OVERWRITE TABLE ods.teacher_contract_signed_time
SELECT
  `id` ,
  `teacher_id` ,
  `weekday` ,
  `start_time` ,
  `end_time` ,
  `signed_id` ,
  `effective_start_time` ,
  `effective_end_time` ,
  `created_at` ,
  `updated_at` ,
  load_time
FROM stg.teacher_contract_signed_time
WHERE etl_date = '{{ macros.ds(ti) }}'; 


