-- This script was auto generated by dataship on 2019-03-07 15:23 

DROP TABLE  if exists tmp.tmp_bk_leave; 
CREATE TABLE tmp.tmp_bk_leave 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`type`, t2.`type`) as `type`,
  coalesce(t1.`typecn`, t2.`typecn`) as `typecn`,
  coalesce(t1.`uid`, t2.`uid`) as `uid`,
  coalesce(t1.`uname`, t2.`uname`) as `uname`,
  coalesce(t1.`classTimeId`, t2.`classTimeId`) as `classTimeId`,
  coalesce(t1.`starttime`, t2.`starttime`) as `starttime`,
  coalesce(t1.`endtime`, t2.`endtime`) as `endtime`,
  coalesce(t1.`shid`, t2.`shid`) as `shid`,
  coalesce(t1.`display`, t2.`display`) as `display`,
  coalesce(t1.`addtime`, t2.`addtime`) as `addtime`,
  coalesce(t1.`edittime`, t2.`edittime`) as `edittime`,
  coalesce(t1.`notes`, t2.`notes`) as `notes`,
  coalesce(t1.`pic`, t2.`pic`) as `pic`,
  coalesce(t1.`namepic`, t2.`namepic`) as `namepic`,
  coalesce(t1.`leave_type`, t2.`leave_type`) as `leave_type`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`leave_notes`, t2.`leave_notes`) as `leave_notes`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `type`, 
    `typecn`, 
    `uid`, 
    `uname`, 
    `classTimeId`, 
    `starttime`, 
    `endtime`, 
    `shid`, 
    `display`, 
    `addtime`, 
    `edittime`, 
    `notes`, 
    `pic`, 
    `namepic`, 
    `leave_type`, 
    `status`, 
    `leave_notes`, 
    `load_time` 
  FROM stg.sishu_bk_leave 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `type`, 
    `typecn`, 
    `uid`, 
    `uname`, 
    `classTimeId`, 
    `starttime`, 
    `endtime`, 
    `shid`, 
    `display`, 
    `addtime`, 
    `edittime`, 
    `notes`, 
    `pic`, 
    `namepic`, 
    `leave_type`, 
    `status`, 
    `leave_notes`, 
    `load_time`
  FROM ods.sishu_bk_leave 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.sishu_bk_leave  
SELECT
  `id`, 
  `type`, 
  `typecn`, 
  `uid`, 
  `uname`, 
  `classTimeId`, 
  `starttime`, 
  `endtime`, 
  `shid`, 
  `display`, 
  `addtime`, 
  `edittime`, 
  `notes`, 
  `pic`, 
  `namepic`, 
  `leave_type`, 
  `status`, 
  `leave_notes`, 
  `load_time`
FROM tmp.tmp_bk_leave; 

