-- This script was auto generated by dataship on 2019-03-07 15:23 

DROP TABLE  if exists tmp.tmp_teacher_leave; 
CREATE TABLE tmp.tmp_teacher_leave 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`teacher_user_id`, t2.`teacher_user_id`) as `teacher_user_id`,
  coalesce(t1.`type`, t2.`type`) as `type`,
  coalesce(t1.`start_time`, t2.`start_time`) as `start_time`,
  coalesce(t1.`end_time`, t2.`end_time`) as `end_time`,
  coalesce(t1.`leave_remark`, t2.`leave_remark`) as `leave_remark`,
  coalesce(t1.`is_check`, t2.`is_check`) as `is_check`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`create_at`, t2.`create_at`) as `create_at`,
  coalesce(t1.`update_at`, t2.`update_at`) as `update_at`,
  coalesce(t1.`is_view`, t2.`is_view`) as `is_view`,
  coalesce(t1.`operator_id`, t2.`operator_id`) as `operator_id`,
  coalesce(t1.`operator_type`, t2.`operator_type`) as `operator_type`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `teacher_user_id`, 
    `type`, 
    `start_time`, 
    `end_time`, 
    `leave_remark`, 
    `is_check`, 
    `status`, 
    `create_at`, 
    `update_at`, 
    `is_view`, 
    `operator_id`, 
    `operator_type`, 
    `load_time` 
  FROM stg.newuuabc_teacher_leave 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `teacher_user_id`, 
    `type`, 
    `start_time`, 
    `end_time`, 
    `leave_remark`, 
    `is_check`, 
    `status`, 
    `create_at`, 
    `update_at`, 
    `is_view`, 
    `operator_id`, 
    `operator_type`, 
    `load_time`
  FROM ods.newuuabc_teacher_leave 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.newuuabc_teacher_leave  
SELECT
  `id`, 
  `teacher_user_id`, 
  `type`, 
  `start_time`, 
  `end_time`, 
  `leave_remark`, 
  `is_check`, 
  `status`, 
  `create_at`, 
  `update_at`, 
  `is_view`, 
  `operator_id`, 
  `operator_type`, 
  `load_time`
FROM tmp.tmp_teacher_leave; 

