-- This script was auto generated by dataship on 2018-12-12 10:21 

DROP TABLE  if exists tmp.tmp_contract; 
CREATE TABLE tmp.tmp_contract 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`template_id`, t2.`template_id`) as `template_id`,
  coalesce(t1.`student_id`, t2.`student_id`) as `student_id`,
  coalesce(t1.`direct_id`, t2.`direct_id`) as `direct_id`,
  coalesce(t1.`contract_type`, t2.`contract_type`) as `contract_type`,
  coalesce(t1.`status`, t2.`status`) as `status`,
  coalesce(t1.`create_admin_id`, t2.`create_admin_id`) as `create_admin_id`,
  coalesce(t1.`create_admin_name`, t2.`create_admin_name`) as `create_admin_name`,
  coalesce(t1.`comment`, t2.`comment`) as `comment`,
  coalesce(t1.`is_display`, t2.`is_display`) as `is_display`,
  coalesce(t1.`start_time`, t2.`start_time`) as `start_time`,
  coalesce(t1.`is_del`, t2.`is_del`) as `is_del`,
  coalesce(t1.`create_at`, t2.`create_at`) as `create_at`,
  coalesce(t1.`update_at`, t2.`update_at`) as `update_at`,
  coalesce(t1.`sucess_at`, t2.`sucess_at`) as `sucess_at`,
  coalesce(t1.`attribute`, t2.`attribute`) as `attribute`,
  coalesce(t1.`contract_amount`, t2.`contract_amount`) as `contract_amount`,
  coalesce(t1.`golds`, t2.`golds`) as `golds`,
  coalesce(t1.`golds_free`, t2.`golds_free`) as `golds_free`,
  coalesce(t1.`leave_total`, t2.`leave_total`) as `leave_total`,
  coalesce(t1.`leave_count`, t2.`leave_count`) as `leave_count`,
  coalesce(t1.`leave_free`, t2.`leave_free`) as `leave_free`,
  coalesce(t1.`leave_free_total`, t2.`leave_free_total`) as `leave_free_total`,
  coalesce(t1.`book`, t2.`book`) as `book`,
  coalesce(t1.`main_class`, t2.`main_class`) as `main_class`,
  coalesce(t1.`add_class`, t2.`add_class`) as `add_class`,
  coalesce(t1.`template_comment`, t2.`template_comment`) as `template_comment`,
  coalesce(t1.`show_amount`, t2.`show_amount`) as `show_amount`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `template_id`, 
    `student_id`, 
    `direct_id`, 
    `contract_type`, 
    `status`, 
    `create_admin_id`, 
    `create_admin_name`, 
    `comment`, 
    `is_display`, 
    `start_time`, 
    `is_del`, 
    `create_at`, 
    `update_at`, 
    `sucess_at`, 
    `attribute`, 
    `contract_amount`, 
    `golds`, 
    `golds_free`, 
    `leave_total`, 
    `leave_count`, 
    `leave_free`, 
    `leave_free_total`, 
    `book`, 
    `main_class`, 
    `add_class`, 
    `template_comment`, 
    `show_amount`, 
    `load_time` 
  FROM stg.newuuabc_contract 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `template_id`, 
    `student_id`, 
    `direct_id`, 
    `contract_type`, 
    `status`, 
    `create_admin_id`, 
    `create_admin_name`, 
    `comment`, 
    `is_display`, 
    `start_time`, 
    `is_del`, 
    `create_at`, 
    `update_at`, 
    `sucess_at`, 
    `attribute`, 
    `contract_amount`, 
    `golds`, 
    `golds_free`, 
    `leave_total`, 
    `leave_count`, 
    `leave_free`, 
    `leave_free_total`, 
    `book`, 
    `main_class`, 
    `add_class`, 
    `template_comment`, 
    `show_amount`, 
    `load_time`
  FROM ods.newuuabc_contract 
) t2 
on t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.newuuabc_contract  
SELECT
  `id`, 
  `template_id`, 
  `student_id`, 
  `direct_id`, 
  `contract_type`, 
  `status`, 
  `create_admin_id`, 
  `create_admin_name`, 
  `comment`, 
  `is_display`, 
  `start_time`, 
  `is_del`, 
  `create_at`, 
  `update_at`, 
  `sucess_at`, 
  `attribute`, 
  `contract_amount`, 
  `golds`, 
  `golds_free`, 
  `leave_total`, 
  `leave_count`, 
  `leave_free`, 
  `leave_free_total`, 
  `book`, 
  `main_class`, 
  `add_class`, 
  `template_comment`, 
  `show_amount`, 
  `load_time`
FROM tmp.tmp_contract; 

