-- This script was auto generated by dataship on 2018-12-12 10:20 

INSERT OVERWRITE TABLE ods.newuuabc_course_details
SELECT
  id ,
  appoint_course_id ,
  class_appoint_course_id ,
  student_id ,
  teacher_into_time ,
  teacher_out_time ,
  student_into_time ,
  student_out_time ,
  patriarch_click_time ,
  patriarch_in_time ,
  student_stream ,
  teacher_stream ,
  page ,
  harvest ,
  gid ,
  graffiti_switch ,
  balance ,
  voice_switch ,
  stage_switch ,
  login_ip ,
  teacher_login_id ,
  point ,
  student_click_time ,
  teacher_click_time ,
  animate_switch ,
  type ,
  platform ,
  load_time
FROM stg.newuuabc_course_details
WHERE etl_date = '{{ macros.ds(ti) }}'; 


