-- This script was auto generated by dataship on 2019-03-14 14:33 

DROP TABLE  if exists tmp.tmp_bk_department; 
CREATE TABLE tmp.tmp_bk_department 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`parentid`, t2.`parentid`) as `parentid`,
  coalesce(t1.`dpname`, t2.`dpname`) as `dpname`,
  coalesce(t1.`dporder`, t2.`dporder`) as `dporder`,
  coalesce(t1.`admin_set`, t2.`admin_set`) as `admin_set`,
  coalesce(t1.`ec_deptId`, t2.`ec_deptId`) as `ec_deptId`,
  coalesce(t1.`create_time`, t2.`create_time`) as `create_time`,
  coalesce(t1.`update_time`, t2.`update_time`) as `update_time`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `parentid`, 
    `dpname`, 
    `dporder`, 
    `admin_set`, 
    `ec_deptId`, 
    `create_time`, 
    `update_time`, 
    `load_time` 
  FROM stg.sishu_bk_department 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `parentid`, 
    `dpname`, 
    `dporder`, 
    `admin_set`, 
    `ec_deptId`, 
    `create_time`, 
    `update_time`, 
    `load_time`
  FROM ods.sishu_bk_department 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.sishu_bk_department  
SELECT
  `id`, 
  `parentid`, 
  `dpname`, 
  `dporder`, 
  `admin_set`, 
  `ec_deptId`, 
  `create_time`, 
  `update_time`, 
  `load_time`
FROM tmp.tmp_bk_department; 

