-- This script was auto generated by dataship on 2019-01-21 19:09 

DROP TABLE  if exists tmp.tmp_teacher_contract; 
CREATE TABLE tmp.tmp_teacher_contract 
USING PARQUET
AS SELECT
  coalesce(t1.`id`, t2.`id`) as `id`,
  coalesce(t1.`signed_id`, t2.`signed_id`) as `signed_id`,
  coalesce(t1.`salary`, t2.`salary`) as `salary`,
  coalesce(t1.`salary_class`, t2.`salary_class`) as `salary_class`,
  coalesce(t1.`salary_live`, t2.`salary_live`) as `salary_live`,
  coalesce(t1.`open_course`, t2.`open_course`) as `open_course`,
  coalesce(t1.`absenteeism`, t2.`absenteeism`) as `absenteeism`,
  coalesce(t1.`wait`, t2.`wait`) as `wait`,
  coalesce(t1.`subsidy`, t2.`subsidy`) as `subsidy`,
  coalesce(t1.`effective_start_time`, t2.`effective_start_time`) as `effective_start_time`,
  coalesce(t1.`effective_end_time`, t2.`effective_end_time`) as `effective_end_time`,
  coalesce(t1.`created_at`, t2.`created_at`) as `created_at`,
  coalesce(t1.`updated_at`, t2.`updated_at`) as `updated_at`,
  coalesce(t1.`enable`, t2.`enable`) as `enable`,
  coalesce(t1.`load_time`, t2.`load_time`) as `load_time`
FROM(SELECT
    `id`, 
    `signed_id`, 
    `salary`, 
    `salary_class`, 
    `salary_live`, 
    `open_course`, 
    `absenteeism`, 
    `wait`, 
    `subsidy`, 
    `effective_start_time`, 
    `effective_end_time`, 
    `created_at`, 
    `updated_at`, 
    `enable`, 
    `load_time` 
  FROM stg.teacher_contract_teacher_contract 
  WHERE etl_date = '{{ macros.ds(ti) }}' 
) AS t1
FULL JOIN  
  (SELECT 
    `id`, 
    `signed_id`, 
    `salary`, 
    `salary_class`, 
    `salary_live`, 
    `open_course`, 
    `absenteeism`, 
    `wait`, 
    `subsidy`, 
    `effective_start_time`, 
    `effective_end_time`, 
    `created_at`, 
    `updated_at`, 
    `enable`, 
    `load_time`
  FROM ods.teacher_contract_teacher_contract 
) t2 
  ON t1.`id` = t2.`id`
;



INSERT OVERWRITE TABLE ods.teacher_contract_teacher_contract  
SELECT
  `id`, 
  `signed_id`, 
  `salary`, 
  `salary_class`, 
  `salary_live`, 
  `open_course`, 
  `absenteeism`, 
  `wait`, 
  `subsidy`, 
  `effective_start_time`, 
  `effective_end_time`, 
  `created_at`, 
  `updated_at`, 
  `enable`, 
  `load_time`
FROM tmp.tmp_teacher_contract; 

