-- This script was auto generated by dataship on 2019-03-19 11:47 

INSERT OVERWRITE TABLE ods.sishu_bk_class_times
SELECT
  `id` ,
  `cl_id` ,
  `cl_date` ,
  `cl_weekid` ,
  `cl_timeid` ,
  `clt_teacher_id` ,
  `status` ,
  `cl_timestart` ,
  `cl_timeend` ,
  `clt_starttime` ,
  `clt_endtime` ,
  `remind` ,
  `sbj_id` ,
  `gensee_in` ,
  `gensee_leave` ,
  `cross_teach_id` ,
  `book_list_id` ,
  `liveroom_type` ,
  `gensee_record_url` ,
  `gensee_record_id` ,
  `gensee_record_token` ,
  `skip` ,
  `already_auto_checked` ,
  `comment_info` ,
  `clt_status` ,
  `courseware_id` ,
  `room_id` ,
  `course_order` ,
  `create_time` ,
  `update_time` ,
  `has_record` ,
  load_time
FROM stg.sishu_bk_class_times
WHERE etl_date = '{{ macros.ds(ti) }}'; 


